name: Cypress Tests

on:
  workflow_dispatch: # Permite disparar a action manualmente

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    env:
      TERM: xterm # Variável de ambiente para o terminal
    steps:
      - name: Get Code # Clona o repositório
        uses: actions/checkout@v4.2.2

      - name: Instalar dependencias # Instala as dependências do projeto
        run: npm install

      - name: Instalar cypress # Instala as dependências do projeto
        run: npm install cypress

      - name: Executar Testes # Executa os testes do Cypress especificando a pasta do projeto
        run: npx cypress run --project ./cypress