name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # <-- THIS IS THE KEY CHANGE

      - name: Install dependencies
        run: npm install

      # Add other steps here, e.g., running tests, building your application
      - name: Run tests
        run: npm test